---
pathPrefix: ../containerSSH-operator/modules-modified 	// prefix to all path
changes:
  "configuration/appconfig.go": 			// file to change
    variables:
      Listen:						// variable anotation should add
      -  "// +optional"					// annotation
    types:
      AppConfig:					// type anotation should add
      -  "// +optional"					// annotation
    packages:
      AppConfig:					// type anotation should add
      -  "// +kubebuilder:validation:Optional"		// annotation
