---
pathPrefix: ../containerSSH-operator/modules-modified 	// prefix to all path
changes:
  "configuration/appconfig.go": 			// file to change
    Listen:						// variable anotation should add
    -  "// +optional"					// annotation
